In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [74]:
heartdisease_data=pd.read_csv("Heart disease prediction.csv")

In [75]:
heartdisease_data.shape

(12000, 28)

In [76]:
heartdisease_data.drop(['Gender','ECG_Result','Smoking_Status','Physical_Activity_Level','Risk_Level'],axis=1,inplace=True)

In [77]:
heartdisease_data.head()

,Age,Gender_M,Gender_F,Resting_BP,Cholesterol,Fasting_Blood_Sugar,Max_Heart_Rate,ECG_Result_N,ECG_Result_S,ECG_Result_L,...,Physical_Activity_Level_E,Diet_Quality_Score,Sleep_Hours,BMI,Diabetes,Hypertension,Family_History,Risk_Score,Risk_Level_E,Heart_Disease
0,62,1,0,100,166,84,164,1,0,0,...,1,9,5,18,0,1,1,28.09,3,0
1,52,0,1,107,214,71,173,1,0,0,...,3,7,5,21,0,0,0,16.27,3,0
2,64,1,0,137,184,70,159,1,0,0,...,3,6,9,29,0,1,0,43.55,2,0
3,77,1,0,152,142,92,157,0,1,0,...,2,8,8,25,0,1,0,50.84,2,0
4,51,0,1,119,174,161,171,0,1,0,...,1,7,7,23,1,0,0,40.87,2,0

In [78]:
x=heartdisease_data

In [79]:
x.head()

,Age,Gender_M,Gender_F,Resting_BP,Cholesterol,Fasting_Blood_Sugar,Max_Heart_Rate,ECG_Result_N,ECG_Result_S,ECG_Result_L,...,Physical_Activity_Level_E,Diet_Quality_Score,Sleep_Hours,BMI,Diabetes,Hypertension,Family_History,Risk_Score,Risk_Level_E,Heart_Disease
0,62,1,0,100,166,84,164,1,0,0,...,1,9,5,18,0,1,1,28.09,3,0
1,52,0,1,107,214,71,173,1,0,0,...,3,7,5,21,0,0,0,16.27,3,0
2,64,1,0,137,184,70,159,1,0,0,...,3,6,9,29,0,1,0,43.55,2,0
3,77,1,0,152,142,92,157,0,1,0,...,2,8,8,25,0,1,0,50.84,2,0
4,51,0,1,119,174,161,171,0,1,0,...,1,7,7,23,1,0,0,40.87,2,0

In [80]:
x.isna().sum()

Age                          0
Gender_M                     0
Gender_F                     0
Resting_BP                   0
Cholesterol                  0
Fasting_Blood_Sugar          0
Max_Heart_Rate               0
ECG_Result_N                 0
ECG_Result_S                 0
ECG_Result_L                 0
Smoking_Status_N             0
Smoking_Status_C             0
Alcohol_Consumption          0
Physical_Activity_Level_E    0
Diet_Quality_Score           0
Sleep_Hours                  0
BMI                          0
Diabetes                     0
Hypertension                 0
Family_History               0
Risk_Score                   0
Risk_Level_E                 0
Heart_Disease                0
dtype: int64

In [81]:
x.shape

(12000, 23)

In [82]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        12000 non-null  int64
 1   Gender_M                   12000 non-null  int64
 2   Gender_F                   12000 non-null  int64
 3   Resting_BP                 12000 non-null  int64
 4   Cholesterol                12000 non-null  int64
 5   Fasting_Blood_Sugar        12000 non-null  int64
 6   Max_Heart_Rate             12000 non-null  int64
 7   ECG_Result_N               12000 non-null  int64
 8   ECG_Result_S               12000 non-null  int64
 9   ECG_Result_L               12000 non-null  int64
 10  Smoking_Status_N           12000 non-null  int64
 11  Smoking_Status_C           12000 non-null  int64
 12  Alcohol_Consumption        12000 non-null  int64
 13  Physical_Activity_Level_E  12000 non-null  int64
 14  Diet_Quality_Score         12000 non-null  int64
 15  Sleep_Hours                12000 non-null  int64
 16  BMI                        12000 non-null  int64
 17  Diabetes                   12000 non-null  int64
 18  Hypertension               12000 non-null  int64
 19  Family_History             12000 non-null  int64
 20  Risk_Score                 12000 non-null  float64
 21  Risk_Level_E               12000 non-null  int64
 22  Heart_Disease              12000 non-null  int64
dtypes: float64(1), int64(22)
memory usage: 2.1 MB

In [83]:
x.describe()

,Age,Gender_M,Gender_F,Resting_BP,Cholesterol,Fasting_Blood_Sugar,Max_Heart_Rate,ECG_Result_N,ECG_Result_S,ECG_Result_L,...,Physical_Activity_Level_E,Diet_Quality_Score,Sleep_Hours,BMI,Diabetes,Hypertension,Family_History,Risk_Score,Risk_Level_E,Heart_Disease
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,...,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,54.412833,0.539917,0.460083,117.540750,190.441417,103.880750,165.489667,0.595667,0.250500,0.153833,...,2.140583,5.999417,7.000833,25.620417,0.220667,0.368833,0.291750,32.116545,2.590333,0.009833
std,14.773132,0.498425,0.498425,15.997724,31.213703,29.083701,17.817099,0.490783,0.433319,0.360804,...,0.728604,1.926021,1.027742,3.577974,0.414713,0.482509,0.454587,13.564508,0.511235,0.098679
min,18.000000,0.000000,0.000000,90.000000,120.000000,70.000000,93.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,4.000000,15.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,44.000000,0.000000,0.000000,106.000000,169.000000,83.000000,153.000000,0.000000,0.000000,0.000000,...,2.000000,5.000000,6.000000,23.000000,0.000000,0.000000,0.000000,21.707500,2.000000,0.000000
50%,54.000000,1.000000,0.000000,117.000000,190.000000,95.000000,165.000000,1.000000,0.000000,0.000000,...,2.000000,6.000000,7.000000,26.000000,0.000000,0.000000,0.000000,31.520000,3.000000,0.000000
75%,64.000000,1.000000,1.000000,128.000000,212.000000,115.000000,178.000000,1.000000,1.000000,0.000000,...,3.000000,7.000000,8.000000,28.000000,0.000000,1.000000,1.000000,41.380000,3.000000,0.000000
max,90.000000,1.000000,1.000000,179.000000,303.000000,200.000000,210.000000,1.000000,1.000000,1.000000,...,3.000000,10.000000,9.000000,38.000000,1.000000,1.000000,1.000000,82.800000,3.000000,1.000000

In [87]:
x.corr()

,Age,Gender_M,Gender_F,Resting_BP,Cholesterol,Fasting_Blood_Sugar,Max_Heart_Rate,ECG_Result_N,ECG_Result_S,ECG_Result_L,...,Physical_Activity_Level_E,Diet_Quality_Score,Sleep_Hours,BMI,Diabetes,Hypertension,Family_History,Risk_Score,Risk_Level_E,Heart_Disease
Age,1.000000,0.009374,-0.009374,0.433853,0.325150,-0.002221,-0.830256,0.012174,-0.011938,-0.002222,...,0.000639,-0.013228,-0.004425,-0.006825,-0.000955,0.755152,-0.000190,0.656298,-0.570401,0.127732
Gender_M,0.009374,1.000000,-1.000000,-0.008242,-0.010392,-0.004383,-0.005964,0.003978,-0.003469,-0.001245,...,-0.030944,0.001370,0.000749,-0.015594,-0.007539,0.011203,-0.016276,-0.002939,0.006290,-0.018148
Gender_F,-0.009374,-1.000000,1.000000,0.008242,0.010392,0.004383,0.005964,-0.003978,0.003469,0.001245,...,0.030944,-0.001370,-0.000749,0.015594,0.007539,-0.011203,0.016276,0.002939,-0.006290,0.018148
Resting_BP,0.433853,-0.008242,0.008242,1.000000,0.139309,0.010558,-0.354622,0.002693,-0.004899,0.002220,...,0.001035,-0.002394,0.001377,0.005047,0.015377,0.441744,0.006622,0.444175,-0.373472,0.087118
Cholesterol,0.325150,-0.010392,0.010392,0.139309,1.000000,-0.012179,-0.271010,0.003829,0.004351,-0.010433,...,-0.005895,-0.016333,-0.002009,-0.003143,-0.013474,0.243412,0.001854,0.337260,-0.276475,0.061797
Fasting_Blood_Sugar,-0.002221,-0.004383,0.004383,0.010558,-0.012179,1.000000,0.010674,0.007920,-0.015498,0.007840,...,0.002502,0.009183,0.007746,-0.001085,0.847601,0.006549,0.005739,0.357616,-0.281154,0.148421
Max_Heart_Rate,-0.830256,-0.005964,0.005964,-0.354622,-0.271010,0.010674,1.000000,-0.006816,0.010299,-0.003097,...,0.009828,0.010978,0.006409,0.017289,0.010054,-0.625377,0.000274,-0.539673,0.471329,-0.097780
ECG_Result_N,0.012174,0.003978,-0.003978,0.002693,0.003829,0.007920,-0.006816,1.000000,-0.701697,-0.517522,...,0.008183,-0.015326,-0.012715,0.009410,0.008466,0.007946,0.003575,-0.166983,0.134955,-0.052122
ECG_Result_S,-0.011938,-0.003469,0.003469,-0.004899,0.004351,-0.015498,0.010299,-0.701697,1.000000,-0.246499,...,-0.005436,0.014854,0.006642,-0.014620,-0.004324,-0.007060,0.016923,0.115434,-0.090117,0.047637
ECG_Result_L,-0.002222,-0.001245,0.001245,0.002220,-0.010433,0.007840,-0.003097,-0.517522,-0.246499,1.000000,...,-0.004602,0.003007,0.009319,0.004759,-0.006322,-0.002330,-0.025188,0.088504,-0.075343,0.013688
Smoking_Status_N,-0.001069,0.005973,-0.005973,-0.005136,0.007307,-0.003401,0.004797,0.004783,0.007783,-0.015853,...,0.002120,0.002970,0.006462,-0.016523,-0.001876,-0.003012,0.011172,-0.245378,0.184558,-0.087008
Smoking_Status_C,-0.003569,0.015677,-0.015677,-0.003124,-0.018111,-0.002126,0.001264,-0.001399,-0.010226,0.014184,...,0.000475,0.001418,-0.008601,0.008539,-0.001385,-0.003578,0.008835,0.405866,-0.306617,0.144594
Alcohol_Consumption,-0.005126,-0.003876,0.003876,-0.011813,0.002759,0.001498,0.013093,-0.009880,0.002552,0.010373,...,0.001772,-0.007080,-0.001796,0.006922,-0.001286,-0.001389,0.008649,0.084681,-0.068387,0.037510
Physical_Activity_Level_E,0.000639,-0.030944,0.030944,0.001035,-0.005895,0.002502,0.009828,0.008183,-0.005436,-0.004602,...,1.000000,0.012768,0.003739,0.528775,0.008477,0.000896,0.008761,0.152486,-0.117887,0.039888
Diet_Quality_Score,-0.013228,0.001370,-0.001370,-0.002394,-0.016333,0.009183,0.010978,-0.015326,0.014854,0.003007,...,0.012768,1.000000,-0.007157,0.009268,0.006213,-0.018332,-0.001424,-0.067324,0.052657,-0.008301
Sleep_Hours,-0.004425,0.000749,-0.000749,0.001377,-0.002009,0.007746,0.006409,-0.012715,0.006642,0.009319,...,0.003739,-0.007157,1.000000,-0.000889,0.007194,-0.000116,-0.001947,-0.041367,0.023808,-0.009942
BMI,-0.006825,-0.015594,0.015594,0.005047,-0.003143,-0.001085,0.017289,0.009410,-0.014620,0.004759,...,0.528775,0.009268,-0.000889,1.000000,-0.000273,-0.004102,0.003378,0.114918,-0.092947,0.034177
Diabetes,-0.000955,-0.007539,0.007539,0.015377,-0.013474,0.847601,0.010054,0.008466,-0.004324,-0.006322,...,0.008477,0.006213,0.007194,-0.000273,1.000000,0.007634,0.003292,0.390657,-0.307472,0.162841
Hypertension,0.755152,0.011203,-0.011203,0.441744,0.243412,0.006549,-0.625377,0.007946,-0.007060,-0.002330,...,0.000896,-0.018332,-0.000116,-0.004102,0.007634,1.000000,0.002551,0.656329,-0.607399,0.130363
Family_History,-0.000190,-0.016276,0.016276,0.006622,0.001854,0.005739,0.000274,0.003575,0.016923,-0.025188,...,0.008761,-0.001424,-0.001947,0.003378,0.003292,0.002551,1.000000,0.275977,-0.214718,0.092101
Risk_Score,0.656298,-0.002939,0.002939,0.444175,0.337260,0.357616,-0.539673,-0.166983,0.115434,0.088504,...,0.152486,-0.067324,-0.041367,0.114918,0.390657,0.656329,0.275977,1.000000,-0.831727,0.274275
Risk_Level_E,-0.570401,0.006290,-0.006290,-0.373472,-0.276475,-0.281154,0.471329,0.134955,-0.090117,-0.075343,...,-0.117887,0.052657,0.023808,-0.092947,-0.307472,-0.607399,-0.214718,-0.831727,1.000000,-0.308362
Heart_Disease,0.127732,-0.018148,0.018148,0.087118,0.061797,0.148421,-0.097780,-0.052122,0.047637,0.013688,...,0.039888,-0.008301,-0.009942,0.034177,0.162841,0.130363,0.092101,0.274275,-0.308362,1.000000

In [88]:
y=x['Heart_Disease']

In [89]:
 y.head()

0    0
1    0
2    0
3    0
4    0
Name: Heart_Disease, dtype: int64

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

In [48]:
y_test.head()

1935    0
6494    0
1720    0
9120    0
360     0
Name: Heart_Disease, dtype: int64

In [49]:
model=LogisticRegression()

In [50]:
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'Female'